name: RHIZA

permissions:
  contents: read

on:
  push:
  pull_request:
    branches: [ main, master ]

jobs:
  validation:
    runs-on: ubuntu-latest
    # don't run this in rhiza itself. Rhiza has no template.yml file. 
    if: ${{ github.repository != 'jebel-quant/rhiza' }}
    container:
      image: ghcr.io/astral-sh/uv:0.9.18-python3.12-trixie

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Validate Rhiza config
        shell: bash
        run: |
          python -m pip install rhiza --index-url https://pypi.org/simple
          rhiza validate
